/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ProjectsList = ProjectsListItem[];

export interface ProjectsListItem {
  id: number;
  name: string;
  tasksCompleted: number;
  tasksTotal: number;
}
