/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectDetails {
  id: number;
  name: string;
  tasks: TasksListItem[];
}
export interface TasksListItem {
  id: number;
  name: string;
  status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
}
