on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
      - run: yarn install
      - name: Build an application
      - run: yarn build
      - name: Run E2E tests
      - run: yarn ci
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.DEV_API_URL }}
      - name: Upload reports to Katalon TestOps
        uses: katalon-studio/report-uploader@v0.0.8
        env:
          PASSWORD: ${{ secrets.KATALON_PASSWORD }}
          PROJECT_ID: ${{ secrets.KATALON_PROJECT_ID }}
          TYPE: junit
          REPORT_PATH: e2e/reports
